<?php
$pageTitle='Users';ob_start();?>
<div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Users</h5><div>
<a href="/admin/roles" class="btn btn-outline-secondary btn-sm me-2">Roles &amp; Permissions</a><a href="/admin/activity-logs" class="btn btn-outline-secondary btn-sm me-2">Activity Logs</a><a href="/admin/users/create" class="btn btn-primary btn-sm"><i class="fa-solid fa-plus me-1"></i>Add User / Role</a></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><table class="table table-hover align-middle"><thead><tr><th>Name</th><th>Email</th><th>Roles</th><th>Default Home</th><th>Status</th><th>Last Login</th><th></th></tr></thead><tbody>
<?php foreach($users as $user): ?><tr><td><?= htmlspecialchars($user['name']) ?></td><td><?= htmlspecialchars($user['email']) ?></td><td><?php foreach(explode(', ',(string)$user['role_names']) as $rn): ?><?php if($rn!==''): ?><span class="badge bg-secondary me-1"><?= htmlspecialchars($rn) ?></span><?php endif; ?><?php endforeach; ?></td>
<td><?php if(!empty($user['default_member_id'])&&$user['default_flat_number']): ?><span class="fw-semibold"><?= htmlspecialchars(($user['default_wing_name']??'').'-'.$user['default_flat_number']) ?></span><small class="text-muted d-block"><?= htmlspecialchars($user['default_member_name']??'') ?></small><?php else: ?>—<?php endif; ?></td>
<td><?php $badge=match($user['status']){'active'=>'success','locked'=>'danger',default=>'secondary'}; ?><span class="badge bg-<?= $badge ?>"><?= ucfirst($user['status']) ?></span></td><td><small><?= htmlspecialchars($user['last_login_at']??'Never') ?></small></td>
<td class="text-end"><button class="btn btn-sm btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#manage-<?= (int)$user['id'] ?>">Manage</button></td></tr>
<tr class="collapse" id="manage-<?= (int)$user['id'] ?>"><td colspan="7"><div class="row g-3 p-2">
<div class="col-lg-7"><h6>Role assignments</h6><?php $assignments=\App\Models\User::rolesForUser((int)$user['id']);foreach($assignments as $a): ?><div class="d-flex align-items-center justify-content-between border rounded p-2 mb-2"><div><span class="badge bg-primary"><?= htmlspecialchars($a['role_name']) ?></span><?php if(!empty($a['is_default'])): ?><span class="badge bg-success ms-1">Default</span><?php endif; ?><span class="small ms-2"><?= htmlspecialchars(($a['wing_name']??'').'-'.($a['flat_number']??'').' — '.($a['member_name']??'')) ?></span></div><div class="d-flex gap-1">
<?php if(empty($a['is_default'])): ?><form method="post" action="/admin/users/<?= (int)$user['id'] ?>/roles/<?= (int)$a['role_id'] ?>/default"><?= \App\Helpers\Csrf::field() ?><button class="btn btn-sm btn-outline-success">Default</button></form><?php endif; ?>
<?php if(count($assignments)>1): ?><form method="post" action="/admin/users/<?= (int)$user['id'] ?>/roles/<?= (int)$a['role_id'] ?>/remove"><?= \App\Helpers\Csrf::field() ?><button class="btn btn-sm btn-outline-danger">Remove</button></form><?php endif; ?></div></div><?php endforeach; ?></div>
<div class="col-lg-5"><h6>Add role</h6><form method="post" action="/admin/users/<?= (int)$user['id'] ?>/roles"><?= \App\Helpers\Csrf::field() ?><select name="role_id" class="form-select form-select-sm mb-2 js-role-for-user"><option value="">Select role</option><?php foreach($roles as $r): ?><option value="<?= (int)$r['id'] ?>"><?= htmlspecialchars($r['name']) ?></option><?php endforeach; ?></select>
<select name="member_id" class="form-select form-select-sm mb-2 js-linked-home" data-user-id="<?= (int)$user['id'] ?>" disabled required><option value="0">Select role first</option></select><button class="btn btn-sm btn-primary">Add Role</button></form>
<hr><h6>Account status</h6><form method="post" action="/admin/users/<?= (int)$user['id'] ?>/status"><?= \App\Helpers\Csrf::field() ?><select name="status" class="form-select form-select-sm mb-2"><option value="active" <?= $user['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $user['status']==='inactive'?'selected':'' ?>>Inactive</option><option value="locked" <?= $user['status']==='locked'?'selected':'' ?>>Locked</option></select><button class="btn btn-sm btn-outline-secondary">Save Status</button></form>
<form method="post" action="/admin/users/<?= (int)$user['id'] ?>/reset-password" class="mt-3"><?= \App\Helpers\Csrf::field() ?><div class="input-group input-group-sm"><input type="password" name="password" class="form-control" minlength="8" placeholder="New password" required><button class="btn btn-outline-danger">Reset</button></div></form></div>
</div></td></tr><?php endforeach; ?><?php if(empty($users)): ?><tr><td colspan="7" class="text-center text-muted py-4">No users yet.</td></tr><?php endif; ?></tbody></table></div></div>
<script>
(function(){async function load(form){const role=form.querySelector('.js-role-for-user'),home=form.querySelector('.js-linked-home');if(!role||!home)return;home.disabled=true;home.innerHTML='<option>Loading available homes…</option>';if(!role.value){home.innerHTML='<option value="0">Select role first</option>';return;}try{const r=await fetch('/admin/users/resident-candidates?role_id='+encodeURIComponent(role.value)+'&user_id='+encodeURIComponent(home.dataset.userId),{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();const d=await r.json();home.innerHTML='';if(!d.items||!d.items.length){home.append(new Option('No available homes for this role','0'));return;}home.append(new Option('Select home','0'));d.items.forEach(i=>home.append(new Option(i.wing_name+'-'+i.flat_number+' — '+i.name+' ('+i.member_type+')',i.id)));home.disabled=false;}catch(e){home.innerHTML='<option value="0">Could not load available homes</option>';}}
document.querySelectorAll('.js-role-for-user').forEach(r=>r.addEventListener('change',()=>load(r.closest('form'))));})();
</script>
<?php $content=ob_get_clean();require __DIR__.'/../layouts/app.php';