<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
    .header { text-align: center; margin-bottom: 16px; }
    .header h2 { margin: 0; }
    .header h3 { margin: 4px 0 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    td, th { padding: 5px 4px; border-bottom: 1px solid #ddd; text-align: left; }
    th { background: #f0f0f0; }
    .footer { margin-top: 20px; font-size: 9px; color: #777; text-align: center; }
</style>
</head>
<body>
    <div class="header">
        <h2><?= htmlspecialchars($society['name'] ?? 'SocietyOS') ?></h2>
        <p><?= htmlspecialchars($society['address'] ?? '') ?></p>
        <h3><?= htmlspecialchars($title) ?></h3>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach (array_keys($headers) as $label): ?>
                    <th><?= htmlspecialchars($label) ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($rows as $row): ?>
                <tr>
                    <?php foreach ($headers as $key): ?>
                        <td><?= htmlspecialchars((string) ($row[$key] ?? '')) ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($rows)): ?>
                <tr><td colspan="<?= count($headers) ?>" style="text-align:center;">No data for this report.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        Generated by SocietyOS on <?= htmlspecialchars(date('Y-m-d H:i')) ?>
    </div>
</body>
</html>
